language: scala
scala:
  - 2.12.10
  - 2.13.1

jdk: openjdk8

sudo: false

script:
  - set -e
  - sbt test transferPublishAndTagResources
  - scripts/publishAndTag 'slamdata/scala-pathy'

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
