language: scala

scala:
  - 2.12.10
  - 2.13.1

jdk: openjdk8

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "n5fzulfj1q/8jX303kHRYA8h1YgXmqgdUW/SRr1AEuOAQO9h0G/7r7afuJguKp7gLOEh2EblKv2kBR/8xfbXfe1ZwwHcm9OmgF4WfNpygZJn+btA+XmrqjXQsQRhIiCapNWHh5QafoyhYyhiUg5DZIbefIOPGAgvoyUoa/n5DFn/uMBcW6Zt3M4dLt5CXZyi6kiEg+KfY3KW16YSZN3yGAtJ5I+/IJ0P+Bv4v9uPq4xu7vkZLNKa2n3aVnzvE5ENP8Gv0v2Ufg0K1BPDK6WNMWMnyfP1lABjRx3ClsEXn9KVtvC3dCuakDExW2tfu3xFDCCYgIbSbIbNTqQ60wxmsub3KG88K7oMh2NSJLnyQftdz8S8taJMu6pcxjTk0cdGixky/Y0p3b9lRebISwj9XWilnpiNk9H8hl7AqNJtsoaL+2iFpf0ZV8CbJ6sn9weN9mlWTtN/94+00/PgkmP1jzTP9bOEa+wkX1SyEHdt4TFPWKLDdWO7HQ3ofahVcvzL/qlj8CXTILEnympRtl2f68l+T+6w4EYjMHoSJTVfA0dmCl96sEru33IXdooP50G9XPhtMQXGkgx4Ur5Cmlh5rI5CUoz9VtR+Zc8+QAjiykJrUimg7qOqvORIaB3ZnEfbo9hA6qLu0t+dlkIL2XFRboehP5LjAJoHjS3n5qRTMJo="
    # GITHUB_TOKEN
    - secure: "eN+Ec5IPe46SDQFVLl05tyl+Ib5qBcXN6rZ+kzMWVR0wDT+Xcb9jbnqRh/evYbRa3ndrRaMvcs8waf5J/e//j+yGokpGVwgxhf+dmVOtNsPcfvuPc9PivwSKVN8O08JZ37J+F3yizJ7hCR8hyRacJlhd8YU5mHcrEkIlQX6sXCYZ4qrQlj6/toy6Cj6n1UoVFl+ePhMOz9WVkzKjz040ug6PpP+m6iAlZ6NyG9qSzUX1KaDDwq3H/lnup7eD8LyVGYGDZtAxi5Y1kNZU8oTE4Sr3saY9d5VHeVwhryGYUYpZXw/mXUNJI8twajZWAY5AczAUT5og93iY4I+FE2dNakCZj6PNs7FzBl8TEOh4eZ0j23wKZoOsKo7BHLKo1vywQjpdKCyH3jk1VM2mxFMFk4HzKGTuIb3kQbtHQNir3cbvt2Jhh314uYHaJ7J5MidHaNiKMlqTemeM+Wp/xs3GHT2wDfE8IHqtlJ3ziE15/pUVE1JC141EIQdPS0SnslnYDE0dnIN2A8YEGRvdT08OwYDTwVOBC4k86Gyfwn28aLVPS3EZ7RTk7onPM+5ty31CPgBN6fl8D51apNDMqI7ibmqswVOEfivQ6rUFOM+3N8fxFbJkHGOWw73bfHpXzdtYWKLt0EBFul158C+nQ9h8mYscA0TNLpw3SkbA3c6BgBY="
    # GITHUB_ACCESS_TOKEN
    - secure: "a7KTw2IcrWEL+TPHDvDSZz3wCMOcxJ72C77E0CR3OqyWjKjutntnSvYrp8CZ/e83iavL+BDCIbO8cNJSktBx1/XlLM3r5m/+64MT57BLIaK6UoAxRni5piUhzj7dLQ0BS4ZcvTfK7SMILJGi3Hh0q18H/cN7JUMkmjH3WJAg0WtBf7gSZSGG9HS+WSzoV9zVD1TajmnCFfAcrl6iqA5FQuuOY72c6/x5mwx63vRYhk8VG5gpnkGYfQazot78CZuPzW9SEDPvCc9szdb7WNelmyEVwxKNpXVujNuth61O9huRBRkJFEfUBwE17j/2iBLAAnB7WdbESaMChitqcUwJFJkk377HBkSi9xKVoaXkbvobqaPh26gzLVkvRT06CX3YJHM6ZbiCUyb9aLzy+/iGkfV99tHb4UgBH7gOOiIsN8PMHGc8tHcFR+z52UX2sTwMh3/7BwDVRik0VM/2ETQPMNPvJ+ZRDvXP7sGV1EPixh/o4J1ArpeXpEewIruO80zWdcdMVWF9qDuTeXyhoebrrLDDWeM5iZOdRT36EDGiITlAMc8QmR2kwKXOIEs8a/eQ9xHttr6HMuK8GQ/Avd6TNRx9ToktL/MGXHIy4qiNgfRFqeC3GsQ111qBCVmTmhvLEfvR+V1RmJciGKsO7FqtPNnyVGS3QACxyuASPw0XDF4="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "M+UlQlJ1vEG5fCezGTPYNP/cyiRAGgLAawjdfUI04YWoqamRvDQYn6u4fjHvQu/1V/qt8tSukn8ETuI0kHirqDu79hQE28+BDjH7tWwBlLYoYZpXrLbO62VKkSvkh7wv+FNMnDVzL40pmfs/bMPGcYhXXZiqc/24uRJxlKIzJa77CvI3uKwvYKaxFFFr7IdLvFADfDveVfnbnWT7toeF7wqCW2nqfqqgPpZaJQRkLrggDU3wfSs15HXRuI7RcgxJ/RLC13MbwHAN8FP/JQ8U377AlvnjYSnxdInYYbgcFtlUwkxn1A0RmZ4ed/taxMDTvXAmH8WOFB/C/yCsl1r2iuawhj/fEIkIcsPL9+CqLIUcUChc69Innp0ZYsg21wWkKIftYMqtIDc4EYfvWb2fq/Ch9etfQZsJdG4RMtz4w9nmgINjEWDN5m2a5dxs3DwX288FbL3OxCzWR4ifuwB0EWnMgT4Ax/6fj2FgoRJ3H+ozbCGCv4vSbqextbSWJDLhdf5uBFTWeylNxgY8l1RLrO1hSbNIu/mu9kkqFCE5D9gc89N+yzlUA55lEnnX0kRTyWYqDslKJ+4ERdpDdAH7UjTgIHn97raGWixckTxxvwz+J3vMTa4gX1VhwkKx5xoexbaoQGE9KdnoVRSrrgzn8oGVIH1dWJOgVuZFMnBQSDI="

install:
  - set -e
  - $SBT transferCommonResources
  - scripts/commonSetup

script:
  - set -e
  - $SBT ++$TRAVIS_SCALA_VERSION test
  - |-
    if [[ "$TRAVIS_SCALA_VERSION" =~ 2.12 ]]; then
      if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/scala-pathy'
      fi
    fi

after_success: scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS
after_failure: scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/
